config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :vendors do
      collection do
        post :update_positions
      end
    end
    get 'vendor_settings' => 'vendor_settings#edit'
    patch 'vendor_settings' => 'vendor_settings#update'
  end
end

app/models/spree/vendor.rb
module Spree
  class Vendor < Spree::Base
    extend FriendlyId

    acts_as_paranoid
    acts_as_list column: :priority
    friendly_id :name, use: %i[slugged history]

    validates :name,
              presence: true,
              uniqueness: { case_sensitive: false }

    validates :slug, uniqueness: true
    validates_associated :image if Spree.version.to_f >= 3.6

    validates :notification_email, email: true, allow_blank: true

    with_options dependent: :destroy do
      if Spree.version.to_f >= 3.6
        has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::VendorImage'
      end
      has_many :commissions, class_name: 'Spree::OrderCommission'
      has_many :option_types
      has_many :products
      has_many :properties
      has_many :shipping_methods
      has_many :stock_locations
      has_many :variants
      has_many :vendor_users
    end

    has_many :users, through: :vendor_users

    after_create :create_stock_location
    after_update :update_stock_location_names

    state_machine :state, initial: :pending do
      event :activate do
        transition to: :active
      end

      event :block do
        transition to: :blocked
      end
    end

    scope :active, -> { where(state: 'active') }

    self.whitelisted_ransackable_attributes = %w[name state]

    def update_notification_email(email)
      update(notification_email: email)
    end

    # Spree Globalize support
    # https://github.com/spree-contrib/spree_multi_vendor/issues/104
    if defined?(SpreeGlobalize)
      attr_accessor :translations_attributes
      translates :name,
                 :about_us,
                 :contact_us,
                 :slug, fallbacks_for_empty_translations: true
    end

    private

    def create_stock_location
      stock_locations.where(name: name, country: Spree::Country.default).first_or_create!
    end

    def should_generate_new_friendly_id?
      slug.blank? || name_changed?
    end

    def update_stock_location_names
      if (Spree.version.to_f < 3.5 && self.name_changed?) || (Spree.version.to_f >= 3.5 && saved_changes&.include?(:name))
        stock_locations.update_all({ name: name })
      end
    end
  end
end

app/controllers/spree/admin/vendors_controller.rb
module Spree
  module Admin
    class VendorsController < ResourceController

      def create
        if permitted_resource_params[:image] && Spree.version.to_f >= 3.6
          @vendor.build_image(attachment: permitted_resource_params.delete(:image))
        end
        super
      end

      def update
        if permitted_resource_params[:image] && Spree.version.to_f >= 3.6
          @vendor.create_image(attachment: permitted_resource_params.delete(:image))
        end
        format_translations if defined? SpreeGlobalize
        super
      end

      def update_positions
        params[:positions].each do |id, position|
          vendor = Spree::Vendor.find(id)
          vendor.set_list_position(position)
        end

        respond_to do |format|
          format.js { render plain: 'Ok' }
        end
      end

      private

      def find_resource
        Vendor.with_deleted.friendly.find(params[:id])
      end

      def collection
        params[:q] = {} if params[:q].blank?
        vendors = super.order(priority: :asc)
        @search = vendors.ransack(params[:q])

        @collection = @search.result.
            page(params[:page]).
            per(params[:per_page])
      end

      def format_translations
        params[:vendor][:translations_attributes].each do |_, data|
          translation = @vendor.translations.find_or_create_by(locale: data[:locale])
          translation.name = data[:name]
          translation.about_us = data[:about_us]
          translation.contact_us = data[:contact_us]
          translation.slug = data[:slug]
          translation.save!
        end
      end
    end
  end
end

app/helpers/spree/admin/vendor_helper.rb
module Spree
  module Admin
    module VendorHelper
      def current_spree_vendor
        if current_spree_user.vendors.any? && (!current_spree_user.respond_to?(:has_spree_role?) || !current_spree_user.has_spree_role?(:admin))
          current_spree_user.vendors.first
        end
      end
    end
  end
end

app/views/spree/admin/vendors/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @vendor } %>
<div class="form-group">
  <%= f.field_container :name do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  <% end %>
  <%= f.field_container :about_us do %>
    <%= f.label :about_us %>
    <%= f.text_area :about_us, class: 'form-control' %>
  <% end %>
  <%= f.field_container :contact_us do %>
    <%= f.label :contact_us %>
    <%= f.text_area :contact_us, class: 'form-control' %>
  <% end %>
  <%= f.field_container :state do %>
    <%= f.label :state %>
    <%= f.select :state,
      options_for_select(Spree::Vendor.state_machines[:state].states.collect { |s| [Spree.t("vendor_states.#{s.name}"), s.value] }, selected: @vendor.state),
      {}, class: 'select2', required: :required %>
  <% end %>
  <% if Spree.version.to_f >= 3.6 %>
    <%= f.field_container :image do %>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= image_tag main_app.url_for(@vendor.image.url(:small)) if @vendor.image %>
    <% end %>
  <% end %>
  <%= f.field_container :commission_rate do %>
    <%= f.label :commission_rate %>
    <%= f.number_field :commission_rate, step: '0.01', class: 'form-control' %>
  <% end %>
  <%= f.field_container :notification_email do%>
    <%= f.label :notification_email %>
    <%= f.email_field :notification_email, class: 'form-control' %>
  <% end %>
</div>

app/views/spree/admin/vendors/edit.html.erb
<% content_for :page_title do %>
  <%= link_to plural_resource_name(Spree::Vendor), spree.admin_vendors_url %> /
  <%= @vendor.name %>
<% end %>

<%= form_for [:admin, @vendor] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/vendors/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(plural_resource_name(Spree::Vendor)) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_vendor), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_vendor' } %>
<% end if can?(:create, Spree::Vendor) %>

<% content_for :table_filter do %>
  <div data-hook="admin_vendors_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, tabindex: 1, class: "form-control js-quick-search-target" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= label_tag :q_state_eq, Spree.t(:state) %>
            <%= f.select :state_eq, Spree::Vendor.state_machines[:state].states.collect { |s| [Spree.t("vendor_states.#{s.name}"), s.value] }, { include_blank: true }, class: 'select2 js-filterable' %>
          </div>
        </div>
      </div>
      <div data-hook="admin_vendors_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @vendors.any? %>
  <table class="table sortable" data-hook="vendors_table" data-sortable-link="<%= update_positions_admin_vendors_url %>">
    <thead>
      <tr data-hook="vendors_header">
        <th>
          <%= I18n.t(:priority, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th>
          <%= sort_link @search, :name, I18n.t(:name, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th>
          <%= sort_link @search, :state, I18n.t(:state, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th>
          <%= I18n.t(:about_us, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th>
          <%= I18n.t(:contact_us, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <% if Spree.version.to_f >= 3.6 %>
          <th>
            <%= I18n.t(:image, scope: 'activerecord.attributes.spree/vendor') %>
          </th>
        <% end %>
        <th>
          <%= sort_link @search, :created_at, I18n.t(:created_at, scope: 'activerecord.attributes.spree/vendor') %>
        </th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @vendors.each do |vendor| %>
        <tr id="<%= spree_dom_id vendor %>" data-hook="vendors_row">
          <td class="move-handle text-center">
            <span class="icon icon-move handle"></span>
          </td>
          <td>
            <%= vendor.name %>
          </td>
          <td>
            <span class="label label-<%= vendor.state.downcase %>"><%= vendor.state.humanize.downcase %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= vendor.state %>"></span>
          </td>
          <td>
            <%= vendor.about_us&.truncate(20) %>
          </td>
          <td>
            <%= vendor.contact_us&.truncate(20) %>
          </td>
          <% if Spree.version.to_f >= 3.6 %>
            <td>
              <%= image_tag main_app.url_for(vendor.image.url(:mini)) if vendor.image %>
            </td>
          <% end %>
          <td>
            <%= pretty_time(vendor.created_at) %>
          </td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit vendor, no_text: true, class: 'edit' if can?(:edit, vendor) %>
            <!-- Add translation icon support -->
            <%= link_to_with_icon 'translate',
                                  nil,
                                  spree.admin_translations_path('vendor', vendor.id),
                                  title: Spree.t(:'i18n.translations'),
                                  class: 'btn btn-sm btn-primary' if defined? (SpreeGlobalize)%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Vendor)) %>
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/vendors/new.html.erb
<% content_for :page_title do %>
  <%= link_to plural_resource_name(Spree::Vendor), spree.admin_vendors_url %> /
  <%= Spree.t(:new_vendor) %>
<% end %>

<%= form_for [:admin, @vendor] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>