config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :vendors do
      collection do
        post :update_positions
      end
    end
    get 'vendor_settings' => 'vendor_settings#edit'
    patch 'vendor_settings' => 'vendor_settings#update'
  end
end

app/controllers/spree/admin/vendor_settings_controller.rb
module Spree
  module Admin
    class VendorSettingsController < Spree::Admin::BaseController
      before_action :authorize
      before_action :load_vendor

      def update
        if vendor_params[:image] && Spree.version.to_f >= 3.6
          @vendor.create_image(attachment: vendor_params[:image])
        end
        if @vendor.update(vendor_params.except(:image))
          redirect_to admin_vendor_settings_path
        else
          render :edit
        end
      end

      private

      def authorize
        authorize! :manage, :vendor_settings
      end

      def load_vendor
        @vendor = current_spree_vendor
        raise ActiveRecord::RecordNotFound unless @vendor
      end

      def vendor_params
        params.require(:vendor).permit(Spree::PermittedAttributes.vendor_attributes)
      end
    end
  end
end

app/views/spree/admin/vendor_settings/edit.html.erb
<% content_for :page_title do %>
  <%= @vendor.name %>
<% end %>

<%= form_for [:admin, @vendor], url: admin_vendor_settings_url do |f| %>
  <fieldset>
    <%= render partial: 'spree/shared/error_messages', locals: { target: @vendor } %>
    <div class="form-group">
      <%= f.field_container :name do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      <% end %>
    </div>
    <% if Spree.version.to_f >= 3.6 %>
      <div class="form-group">
        <%= f.field_container :image do %>
          <%= f.label :image %>
          <%= f.file_field :image %>
          <%= image_tag main_app.url_for(@vendor.image.url(:small)) if @vendor.image %>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.field_container :about_us do %>
        <%= f.label :about_us %>
        <%= f.text_area :about_us, class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.field_container :contact_us do %>
        <%= f.label :contact_us %>
        <%= f.text_area :contact_us, class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.field_container :notification_email do %>
        <%= f.label :notification_email %>
        <%= f.email_field :notification_email, class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_vendor_settings_url, icon: 'delete' %>
    </div>
  </fieldset>
<% end %>